### ISSUE TITLE
店舗の画像をアップロード、表示する機能

### ISSUE THREAD

**Issue by tokikaze0604** [SpriytusLtd/spirytus#68]
忘れてタ

**Comment by gyaneman** [comment]
https://github.com/carrierwaveuploader/carrierwave
これ使おうかと思ふ

**Comment by gyaneman** [comment]
http://ruby-rails.hatenadiary.com/entry/20141015/1413300088

**Comment by gyaneman** [comment]
同じ要領でdrinkもやる

**Comment by gyaneman** [comment]
でけた
